inherit_from: .rubocop_todo.yml
AllCops:
  RunRailsCops: true
  Exclude:
    - Guardfile
    - bin/*

# Rails default check path
Rails/DefaultScope:
  Include:
    - app/controllers/
    - app/models/
    - app/helpers/
    - app/validators/
    - app/cells/
    - lib/

Rails/Output:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
