# secrets configuration

# Make sure the secret is at least 30 characters and all random,
# Use `rake secret`.

production: &production
  #secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: dbcae379048ebb545900e67e5e3c6c3a8a74428f6a436d3113a83ff12a1c05368281c9b2eeb8414d7abe184843b7103034090c16a46fd0159cf764787d499a54

  #OAuth
  twitter_key: 12132sferg
  twitter_secret: grg234441233131323r
  facebook_key: 1ewewfe444333
  facebook_secret: sdfrgggggrasssssffdfelsalmvgfblgltgt
  yahoo_key: pppooo0123lfgrp24l67mvbfbf
  yahoo_secret: 980775ui44rfgtdmmkjfcbagtty13411133251
  google_key: 875430454512531oikeuekiiguiiiikhakxzuawrnkfre
  google_secret: 2jkdjgireposokdueumre
  github_key: gigigigi45667473
  github_secret: 245r236745735y25giigigigigiigig5

test:
  <<: *production

development:
  <<: *production
